version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.20
  pre_build:
    commands:
      - echo Start pre_build...
  build:
    commands:
      - echo Start build...
      - go build -o ./myGoApp ./cmd/main.go
  post_build:
    commands:
      # - echo Start post_build...
      # - zip -r myApp.zip ./myGoApp Procfile

artifacts:
  files:
    - myGoApp
    - .ebextensions/**/*
