version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.20
  pre_build:
    commands:
      - echo Start pre_build...
  post_build:
    commands:
      - echo Start build...
      - go build -o target/main.go ./cmd/main.go
artifacts:
  files:
    - main.go
