version: 0.2
phases:
  pre_build:
    commands:
      - echo "Installing dependencies"
  build:
    commands:
      - echo "Building the Go app"
      - cd cmd
      - go build -o myapp
artifacts:
  files:
    - cmd/myapp
