version: 0.2
phases:
  install:
    runtime-versions:
      golang: 1.20
  pre_build:
    commands:
      - echo CODEBUILD_SRC_DIR - $CODEBUILD_SRC_DIR
      - echo GOPATH - $GOPATH
      - echo GOROOT - $GOROOT
  build:
    commands:
      - echo Start build...
      - go build -o ./myGoApp ./cmd/main.go
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - myGoApp
