version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.20
  pre_build:
    commands:
      - echo Start pre_build...
      - go mod init
  build:
    commands:
      - echo Start build...
      - go build -o ./bin/myGoApp ./cmd/main.go
  post_build:
    commands:
      - echo Start post_build...
      - zip -r myApp.zip ./bin/myGoApp Procfile go.mod

artifacts:
  files:
    - myApp.zip
    - Procfile
    - go.mod
    - .ebextensions/**/*
