version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.20
  pre_build:
    commands:
      - echo "Start pre_build..."
      - mkdir -p ./bin/
  build:
    commands:
      - echo "Start build..."
      - go build -o ./bin/myGoApp ./cmd/main.go
  artifacts:
    files:
      - myGoApp
      - Procfile
      - go.mod
      - .ebextensions/**/*
