phases:
  install:
    runtime-versions:
      golang: 1.20
  pre_build:
    commands:
      - echo Start pre_build...
  build:
    commands:
      - echo Start build...
      - go build -o ./bin/myGoApp ./cmd/main.go # Mudança aqui
  post_build:
    commands:
      - echo Start post_build...
      - zip -r myApp.zip ./bin/myGoApp Procfile # E aqui

artifacts:
  files:
    - myApp.zip
    - Procfile # Adicione isso se necessário
    - .ebextensions/**/*
