version: "3"
services:
  otica:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_DATABASE=otica
      - POSTGRESQL_PASSWORD=otica123
